spring:
  datasource:
    url: jdbc:h2:file:/app/data/votedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: false